### ISSUE TITLE
Error running check_performance_regression_on.

### ISSUE THREAD

**Issue by elieteyssedou** [toch/minitest-perf_regression#2]
Hi,

I just ran a test with your check performance regression and I got this :

`````` TablifyTest#test_performance_regression_on_test_base:
NoMethodError: undefined method `to_h' for #<Array:0x007fa7f46d4b58>
    /Library/Ruby/Gems/2.0.0/gems/benchmark-lab-0.0.1/lib/benchmark/lab.rb:68:in `observe_and_summarize'```


Can you help me ?

Elie
``````

**Comment by toch** [comment]
Hi @elieteyssedou , could you confirm me that you are using ruby 2.0?

**Comment by elieteyssedou** [comment]
Yes I am.

**Comment by toch** [comment]
@elieteyssedou that's the reason, `to_h` is not available on `Array` in 2.0. I'll add a comment in README of the this gem and benchmark-lab about which Ruby version is required. Thanks for pointing it.

could you use the version 2.1?

**Comment by elieteyssedou** [comment]
It works, thank you. :+1:

**Comment by toch** [comment]
@elieteyssedou great! FYI, I've bumped a new version `0.0.2` with a clear requirement to at least 2.1

Thanks!

**Comment by elieteyssedou** [comment]
:)
